[phases.install]
dependsOn = ["setup"]
commands = [
  "pip install --no-cache-dir -r requirements.txt",
  "playwright install chromium",
  "playwright install-deps chromium",
]

[phases.setup]
nix = ["python3", "python3-pip"]
